// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var Boxadd, h, w;
    document.onselectstart = function() {
      return false;
    };
    w = window.innerWidth;
    h = window.innerHeight;
    Boxadd = (function() {
      function Boxadd(elem) {
        var addh, addw;
        this.elem = elem;
        addh = Math.floor((Math.random() * 100) + 200);
        addw = Math.floor((Math.random() * 100) + 200);
        this.elem.move = true;
        this.elem.resize = true;
        $(this.elem).addClass("added");
        $(this.elem).css({
          top: Math.floor((Math.random() * (h - 200)) + 1) + "px",
          left: Math.floor((Math.random() * (w - 200)) + 1) + "px",
          width: addw + "px",
          height: addh + "px",
          "background-color": "rgb(" + Math.floor(Math.random() * 256) + "," + Math.floor(Math.random() * 256) + "," + Math.floor(Math.random() * 256) + ")"
        });
        $(this.elem).on("dblclick", function(e) {
          if (e.target == this) {
            return $(e.target).css("background-color", "rgb(" + Math.floor(Math.random() * 256) + "," + Math.floor(Math.random() * 256) + "," + Math.floor(Math.random() * 256) + ")");
          }
        });
        this.elem.movefunc = function() {
          if (this.move) {
            return $(this).on("mousedown.move", function(e) {
              var originx, originy, orix, oriy, x, y;
              if (e.target === this) {
                x = event.pageX;
                y = event.pageY;
                orix = $(e.target).css("left");
                originx = orix.slice(0, orix.length - 2) * 1;
                oriy = $(e.target).css("top");
                originy = oriy.slice(0, oriy.length - 2) * 1;
                $(document).mousemove(function() {
                  $("body").css("cursor", "move");
                  $(e.target).css({
                    top: originy + event.pageY - y + "px",
                    left: originx + event.pageX - x + "px"
                  });
                  return $(e.target).mouseup(function() {
                    $("body").css({
                      cursor: "default"
                    });
                    return $(document).off();
                  });
                });
              }
              return this.move = false;
            });
          }
        };
        this.elem.resizefunc = function() {
          var originx, originy, orix, oriy;
          if (this.resize) {
            orix = $(this).css("width");
            oriy = $(this).css("height");
            originx = orix.slice(0, orix.length - 2) * 1;
            originy = oriy.slice(0, oriy.length - 2) * 1;
            $(this).append("<div class = resize style=\"top:" + (originy - 10) + "px;left:" + (originx - 10) + "px\"></div>");
            $(this).on("mouseover", ".resize", function(e) {
              return $(e.target).css("cursor", "se-resize");
            });
            $(this).on("mousedown.resize", ".resize", function(e) {
              var x, y;
              x = event.pageX;
              y = event.pageY;
              orix = $(e.target).parent().css("width");
              originx = orix.slice(0, orix.length - 2) * 1;
              oriy = $(e.target).parent().css("height");
              originy = oriy.slice(0, oriy.length - 2) * 1;
              return $(document).mousemove(function() {
                var newx, newy;
                $("body").css("cursor", "se-resize");
                newx = originx + event.pageX - x;
                newy = originy + event.pageY - y;
                if (newx < 10) {
                  newx = 10;
                }
                if (newy < 10) {
                  newy = 10;
                }
                $(e.target).parent().css({
                  width: newx + "px",
                  height: newy + "px"
                });
                $(e.target).css({
                  top: (newy - 10) + "px",
                  left: (newx - 10) + "px"
                });
                return $(e.target).mouseup(function() {
                  $("body").css("cursor", "default");
                  return $(document).off();
                });
              });
            });
            return this.resize = false;
          }
        };
        this.elem.unmovefunc = function() {
          if (!this.move) {
            $(this).off("mousedown.move");
            return this.move = true;
          }
        };
        this.elem.unresizefunc = function() {
          if (!this.resize) {
            $(this).off("mousedown.resize", ".resize");
            $(this).children(".resize").remove();
            return this.resize = true;
          }
        };
      }

      return Boxadd;

    })();
    $("#addbox").click(function() {
      var addedbox, box;
      box = document.createElement("div");
      addedbox = new Boxadd(box);
      addedbox.elem.movefunc();
      addedbox.elem.resizefunc();
      $("body").append(addedbox.elem);
    });
    $("#deletebox").click(function() {
      $("body div.added").remove();
    });
    $("#deleteonebox").click(function() {
      $(document).one("mousedown", function(e) {
        console.log(e);
        if ($(e.target).hasClass("added")) {
          $(e.target).remove();
        }
      });
    });
    $("#unmovebox").click(function() {
      $("body div").one("mousedown", function(e) {
        if ($(e.target).hasClass("added")) {
          e.target.unmovefunc();
        }
      });
    });
    $("#unresizebox").click(function() {
      $("body div").one("mousedown", function(e) {
        if ($(e.target).hasClass("added")) {
          e.target.unresizefunc();
        }
      });
    });
    $("#movebox").click(function() {
      $("body div").one("mousedown", function(e) {
        if ($(e.target).hasClass("added")) {
          e.target.movefunc();
        }
      });
    });
    $("#resizebox").click(function() {
      $("body div").one("mousedown", function(e) {
        if ($(e.target).hasClass("added")) {
          e.target.resizefunc();
        }
      });
    });
  });

}).call(this);
